### ISSUE TITLE
Add interval timeout

### ISSUE THREAD

**Issue by zeladada** [andyfleming/interval-promise#14]
A built-in option to stop the current async function execution and try again after a period of time would be useful in applications where the function or promise could hang for a long time or even indefinitely. With a timeout option, the application would be able to stop the execution of the function after a specified number of milliseconds and try the function again or throw a timeout error.

**Comment by andyfleming** [comment]
This could be a nice option to have. I have an implementation in mind. Maybe this can make it into the 2.1 release.

**Comment by andyfleming** [comment]
I'm not sure if this makes sense to be a feature of this library directly. It might be a better practice to use something like `p-timeout` (on top of `interval-promise`) to achieve this.

I'm going to close this for now. If there is significant interest in including this feature directly in the library we can reopen this issue.
