### ISSUE TITLE
Error with create-react-app: Failed to minify interval-promise/src/index.js:8 

### ISSUE THREAD

**Issue by nagarameshreddy** [andyfleming/interval-promise#15]
Failed to minify the code from this file: 

 	./node_modules/interval-promise/src/index.js:8

**Comment by andyfleming** [comment]
I’m not sure if i’ve ran this through a minifier before. Are there any more details with the error? Do you have a minimal code example to reproduce the issue?

**Comment by andyfleming** [comment]
If this is still a issue, please provide some additional info.
