### ISSUE TITLE
let collaborators make this repo mature

### ISSUE THREAD

**Issue by jjangga0214** [andyfleming/interval-promise#17]
Hi.

The last opened issue was on Jan 24. It's been quite long time without any response even though it got 2 thumb ups. If you(@andyfleming ) don't have much time, please let other people manage this repo.   

Thanks.

**Comment by andyfleming** [comment]
Hi, thanks for the feedback. I have not had a chance to do much maintenance on this project, but as far as I know there aren't any outstanding bugs (aside from some tooling issues). There's 100% coverage and it's stable.

Bug reports and PRs are always welcome though.
