### ISSUE TITLE
"Returns a Promise" check is incorrect

### ISSUE THREAD

**Issue by joepie91** [andyfleming/interval-promise#20]
This library currently checks whether the callback returned a Promise by doing `returnVal instanceof Promise`, but this is incorrect; it only considers the global ES6 Promise implementation in the library's scope/realm, and not any other Promise implementations (including cross-realm Promises, non-global polyfills, and other Promises/A+ compliant Promise implementations such as Bluebird).

The correct check, as per the [Promises/A+ specification](https://promisesaplus.com/), would be more something like:

```js
returnVal != null && typeof returnVal.then === "function"
```

**Comment by andyfleming** [comment]
Good catch @joepie91. We'll see if we can get this addressed. 👍
