### ISSUE TITLE
Option to skip first interval

### ISSUE THREAD

**Issue by silverwind** [andyfleming/interval-promise#97]
Sometimes it could be useful to skip the first interval duration and trigger the first function call immediately. I think a option could be exposed like `skipFirstInterval`, default `false`. So instead of

```js
await something();
interval(something, 1000, {iterations: 10});
```
one could write

```js
interval(something, 1000, {iterations: 11, skipFirstInterval: true});
```

**Comment by andyfleming** [comment]
I think it would be clearer to call it `callImmediately`, but I don't currently plan to add this. Thanks!
